### ISSUE TITLE
Icewind Dale 2 German DE dialog.tlk file results in failure

### ISSUE THREAD

**Issue by ghostlyghastly** [btigi/tlktosql#1]
Thank you for this amazing tool! Works great for BG1 BG2 IWD1 PS:T

Unfortunately, the encoding in IWD2 (German) doesn't work.
[iwd2_de_dialog.tlk.zip](https://github.com/btigi/tlktosql/files/10876084/iwd2_de_dialog.tlk.zip)

TlkViewer for example shows:
![image](https://user-images.githubusercontent.com/61316553/222561964-4f9fec0a-0d8a-4d42-9d29-ed5f7d005b7a.png)

```$ ./TlkToSql.exe iwd2de.tlk iwd2de
Unhandled exception. System.ArgumentException: The output char buffer is too small to contain the decoded characters, encoding 'Unicode (UTF-8)' fallback 'System.Text.DecoderReplacementFallback'. (Parameter 'chars')
   at System.Text.Encoding.ThrowCharsOverflow(DecoderNLS decoder, Boolean nothingDecoded)
   at System.Text.Encoding.GetCharsWithFallback(ReadOnlySpan`1 bytes, Int32 originalBytesLength, Span`1 chars, Int32 originalCharsLength, DecoderNLS decoder)
   at System.Text.UTF8Encoding.GetCharsWithFallback(ReadOnlySpan`1 bytes, Int32 originalBytesLength, Span`1 chars, Int32 originalCharsLength, DecoderNLS decoder)
   at System.Text.Encoding.GetCharsWithFallback(Byte* pOriginalBytes, Int32 originalByteCount, Char* pOriginalChars, Int32 originalCharCount, Int32 bytesConsumedSoFar, Int32 charsWrittenSoFar, DecoderNLS decoder)
   at System.Text.Encoding.GetChars(Byte* pBytes, Int32 byteCount, Char* pChars, Int32 charCount, DecoderNLS decoder)
   at System.Text.DecoderNLS.GetChars(Byte* bytes, Int32 byteCount, Char* chars, Int32 charCount, Boolean flush)
   at System.Text.Decoder.GetChars(ReadOnlySpan`1 bytes, Span`1 chars, Boolean flush)
   at System.IO.BinaryReader.InternalReadChars(Span`1 buffer)
   at System.IO.BinaryReader.ReadChars(Int32 count)
   at TlkToSql.Program.TlkFileBinaryReader.ParseFile(BinaryReader br)
   at TlkToSql.Program.TlkFileBinaryReader.Read(Stream s)
   at TlkToSql.Program.TlkFileBinaryReader.Read(String filename)
   at TlkToSql.Program.Main(String[] args)
```

**Comment by btigi** [comment]
This should be resolved in release 0.7, available today :)
